# Generated by Django 4.2.30 on 2026-09-20 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Rohan Yadav', max_length=100)),
                ('brand', models.CharField(default='Rohan Codekage', max_length=100)),
                ('title', models.CharField(default='Student Programmer · Full-Stack Developer · AI Builder · Founder', max_length=200)),
                ('location', models.CharField(default='Nepal', max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('about_statement', models.TextField(blank=True, help_text='Opening quote for About section')),
                ('about_philosophy', models.TextField(blank=True, help_text='Philosophy quote')),
                ('hero_title', models.CharField(default='I build things that turn ideas into reality.', max_length=300)),
                ('hero_subtitle', models.TextField(default="I'm Rohan Yadav — a student programmer, full-stack developer, AI/LLM builder, and tech entrepreneur from Nepal.")),
                ('hero_description', models.TextField(default='I build web applications, SaaS products, AI-powered tools, and experimental systems while constantly exploring what is possible with technology.')),
                ('status_text', models.CharField(default='Currently building', max_length=100)),
                ('email', models.EmailField(default='rohan@example.com', max_length=254)),
                ('github_url', models.URLField(default='https://github.com/Rohan341-dev')),
                ('linkedin_url', models.URLField(default='https://np.linkedin.com/in/rohan-codekage-746656356')),
                ('instagram_url', models.URLField(default='https://www.instagram.com/rohanl2l')),
                ('facebook_url', models.URLField(default='https://www.facebook.com/rohanl2l')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='TechStackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack_categories', to='core.profile')),
            ],
            options={
                'verbose_name': 'Stack Category',
                'verbose_name_plural': 'Stack Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('journey', 'Journey'), ('founder', 'Founder Journey')], default='journey', max_length=20)),
                ('phase', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='core.profile')),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TechStackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.techstackcategory')),
            ],
            options={
                'verbose_name': 'Stack Item',
                'verbose_name_plural': 'Stack Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=300)),
                ('year', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('product', 'Product'), ('fullstack', 'Full-Stack'), ('ai', 'AI / ML'), ('system', 'System')], max_length=20)),
                ('role', models.CharField(max_length=200)),
                ('focus', models.CharField(max_length=300)),
                ('problem', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated', max_length=500)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.profile')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LeadershipPrinciple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_principles', to='core.profile')),
            ],
            options={
                'verbose_name': 'Leadership Principle',
                'verbose_name_plural': 'Leadership Principles',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='IdentityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_tags', to='core.profile')),
            ],
            options={
                'verbose_name': 'Identity Tag',
                'verbose_name_plural': 'Identity Tags',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExploringItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exploring_items', to='core.profile')),
            ],
            options={
                'verbose_name': 'Exploring Item',
                'verbose_name_plural': 'Exploring Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=300)),
                ('quote', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('services', models.CharField(blank=True, help_text='Comma-separated services', max_length=1000)),
                ('roles', models.CharField(blank=True, help_text='Comma-separated role tags', max_length=500)),
                ('website_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='core.profile')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='certificates/')),
                ('year', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.profile')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BuildingUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_label', models.CharField(default='Recent', max_length=50)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_updates', to='core.profile')),
            ],
            options={
                'verbose_name': 'Building Update',
                'verbose_name_plural': 'Building Updates',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AILabCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('tag', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ailab_cards', to='core.profile')),
            ],
            options={
                'verbose_name': 'AI Lab Card',
                'verbose_name_plural': 'AI Lab Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('year', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.profile')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_highlight', models.BooleanField(default=False, help_text='Highlight this paragraph')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_paragraphs', to='core.profile')),
            ],
            options={
                'verbose_name': 'About Paragraph',
                'verbose_name_plural': 'About Paragraphs',
                'ordering': ['order'],
            },
        ),
    ]
